### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by drcyberg** [ONLYOFFICE/onlyoffice-redmine#26] opened 2022-04-22 11:39 UTC
Hi!
The plugin does not works. Is there any solution to this problem?
Thank you!

**Redmine:**
Environment:
  Redmine version                5.0.0.stable
  Ruby version                   2.7.0-p0 (2019-12-25) [x86_64-linux-gnu]
  Rails version                  6.1.4.7
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  redmine_checklists             3.1.21

**Error:**
log: Creating scope :system. Overwriting existing method Enumeration.system

**Comment by Eloncase** [comment] 2022-07-18 10:42
Duplicate of #27

**Closed by Eloncase** 2022-07-18 10:42 UTC
